name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y google-chrome-stable curl libjemalloc2 libvips sqlite3

      - name: Install dependencies
        run: |
          bundle config set frozen false
          bundle install

      - name: Setup Database
        run: |
          bin/rails db:create
          bin/rails db:migrate
          bin/rails db:test:prepare

      - name: Run tests
        env:
          RAILS_ENV: test
        run: bin/rails test test:system

      - name: Post test result comment with Ruby
        if: always()
        run: |
          gem install octokit
          ruby -e "
          require 'octokit'

          passed = $?.exitstatus == 0  # Check if the exit status is 0 (success)
          comment = passed ? ':white_check_mark: All tests passed! :tada:' : ':x: Some tests failed. Please check the details.'

          pr_number = ENV['GITHUB_REF'].match(/refs\/pull\/(\d+)\/merge/)&.captures&.first

          if pr_number
            client = Octokit::Client.new(access_token: ENV['GITHUB_TOKEN'])
            client.add_comment(ENV['GITHUB_REPOSITORY'], pr_number, comment)
          else
            puts comment
          end
          "
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
