name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y google-chrome-stable curl libjemalloc2 libvips sqlite3
        
      - name: Install dependencies
        run: |
          bundle config set frozen false
          bundle install

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run tests
        env:
          RAILS_ENV: test
        run: bin/rails db:test:prepare test test:system

      - name: Send success notification to Slack
        if: success()
        uses: slackapi/slack-github-action@v1.22.0
        with:
          slack-message: '{"text": "Tests have passed! 🎉"}'
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send failure notification to Slack
        if: failure()
        uses: slackapi/slack-github-action@v1.22.0
        with:
          slack-message: '{"text": "Tests have failed! 😢"}'
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore
